Update gksudo2-su
See readme CHANGELOG

diff --git a/gksudo2-su b/gksudo2-su
--- a/gksudo2-su
+++ b/gksudo2-su
@@ -4,15 +4,37 @@
 #	if tried. This secondary script is called by GKSUDO2 for actions requiring
 #	elevated (sudo) privileges. Required variable assignments are passed in the 
 #	calling statement from GKSUDO2.  Created under GPLv3 license, by
-#	William Rueger (furryfixer). Updated 10/2025.
+#	William Rueger (furryfixer). Updated 07/2026.
 ##=================================================================================##
-err_exit1 () {
-	if ! (zenity --warning --title="gksudo2 Error" --text="$*" --width 600  2>/dev/null); then
+
+err_exit1 () { 
+	if ! dbus-run-session zenity --warning --title="gksudo2 Error" --text="$*" --width 600  &>/dev/null; then
 		echo "$*"  # print error without zenity
 	fi
-	rm $xauth_gksudo 2> /dev/null
-	rm /tmp/gk/gk-env-cmd 2> /dev/null
-	rm /tmp/gk/sudo.gk.error 2> /dev/null
+	finish_cleanup
+	exit 1
+}
+err_exit_file () {  # $1 is title, $2 is header, $3 is filename
+	echo -e "${2}\n$(cat ${3})" > /tmp/gk/err-file-out
+	if ps -e | grep -Eq 'Hyprland|sway|niri|river|dwl|qtile' ; then # Wayland tilers may not float --text-info
+		if ! dbus-run-session zenity --warning --title="${1}" --text="$(cat /tmp/gk/err-file-out)" --width 600 --no-wrap --no-markup --modal &>/dev/null; then
+			cat /tmp/gk/err-file-out  # print error without zenity
+		fi
+	elif ! dbus-run-session zenity --text-info --title="${1} (scrollable)" --width 600 --height 400 --filename /tmp/gk/err-file-out --no-wrap --no-markup --modal &>/dev/null; then
+		cat /tmp/gk/err-file-out  # print error without zenity
+	fi
+	finish_cleanup
+	exit 1
+}
+cleanup_files_dbus () {
+	[[ -s "${as_usr_rundir}/ps-dbus" ]] && read new_dbus < $as_usr_rundir/ps-dbus
+	[[ $new_dbus -ne $last_dbus ]] && kill -- -$new_dbus &>/dev/null
+	[[ -f /tmp/gk/kdeglobals ]] && mv /tmp/gk/kdeglobals /root/.config/kdeglobals
+}
+finish_cleanup () {
+	rm -f $xauth_gksudo 
+	rm -f /tmp/gk/gk-env-cmd
+	rm -f /tmp/gk/sudo.gk.error
 	if [[ -d "$as_usr_rundir" ]]; then
 		umount "$as_usr_rundir/gvfs" 2> /dev/null
 		umount "$as_usr_rundir/doc" 2> /dev/null
@@ -23,23 +45,18 @@ err_exit1 () {
 		chmod 0700 $orig_xdg_rundir
 		chmod 0755 $wayland_socket
 	fi
-	exit 1
 }
-cleanup_files_dbus () {
-	read new_dbus < $as_usr_rundir/ps-dbus
-	[[ $new_dbus -ne $last_dbus ]] && kill -- -$new_dbus
-	[[ -f /tmp/gk/kdeglobals ]] && mv /tmp/gk/kdeglobals /root/.config/kdeglobals
-}
-####
+######
 if [[ -z "$INVOKING_USR" ]]; then
 	err_exit1 "STOP! gksudo2-su improperly called, or
 attempted to run independently of gksudo2 "
 fi
+rm -f /tmp/gk/err-file-out
 as_usr_rundir=$(mktemp -d /tmp/gk/runtime-gksudo-as-$as_user.XXXX)
 chmod 0700 $as_usr_rundir
 chown $as_user $as_usr_rundir
 xauth_gksudo=$(mktemp /tmp/gk/.gk.XXXXXXX)
-cp $XAUTHORITY $xauth_gksudo
+[[ -s "$XAUTHORITY" ]] && cp $XAUTHORITY $xauth_gksudo
 XAUTHORITY=$xauth_gksudo
 chmod 0600 $xauth_gksudo
 chown $as_user $xauth_gksudo
@@ -77,6 +94,8 @@ else # WAYLAND SESSION!
 	else
 		DISPLAY=$(ps eh -e | grep -m 1 ' WAYLAND_DISPLAY' | sed -rn 's/.* DISPLAY=//p' | cut -d " " -f 1)
 	fi
+	# Xwayland may need Xauthority for some compositors. Inexact method
+	[[ -z "${XAUTHORITY}" && -s "${usr_home}/.Xauthority" ]] && XAUTHORITY="${usr_home}/.Xauthority"
 fi
 as_usr_home=$(eval echo "~${as_user}")
 timestamp=`date +%D" "%H:%M:%S`
@@ -119,59 +138,54 @@ else
 fi	
 echo "   ${dbusl_cmd}
    ps > /dev/null   # Only to force update of process tree
-   pgrep -n dbus-daemon > \$XDG_RUNTIME_DIR/ps-dbus
+   pgrep -n dbus-daemon > \${XDG_RUNTIME_DIR}/ps-dbus
    wait \$!" >> /tmp/gk/gk-env-cmd
 # Backgrounding dbus-launch allows to get dbus-daemon PID immediately,
 #    but this forces use of wait to proceed properly after.
 chmod +x /tmp/gk/gk-env-cmd
+failed=false
 last_dbus=$(pgrep -n dbus-daemon)
-if ! sudo -u $INVOKING_USR pkexec --user $as_user /tmp/gk/gk-env-cmd &>/tmp/gk/sudo.gk.error; then # Failed execution
+if ! sudo -u $INVOKING_USR pkexec --user $as_user /tmp/gk/gk-env-cmd >/tmp/gk/sudo.gk.error 2>&1; then # Failed execution
+	cleanup_files_dbus
+	failed=true
+	if grep -q 'open display' /tmp/gk/sudo.gk.error; then 
+		if ! sudo -u $INVOKING_USR xhost | grep -q $as_user ; then  # retry with xhost as last resort 		
+			sudo -u $INVOKING_USR xhost SI:localuser:$as_user &>/dev/null
+			last_dbus=$(pgrep -n dbus-daemon)
+			if sudo -u $INVOKING_USR pkexec --user $as_user /tmp/gk/gk-env-cmd >/tmp/gk/sudo.gk.error 2>&1; then # succeeded
+				failed=false
+			fi
+			cleanup_files_dbus 
+			sudo -u $INVOKING_USR xhost -SI:localuser:$as_user &>/dev/null	
+		fi
+	fi
+else
 	cleanup_files_dbus 
+fi
+if $failed ; then	
 	if [[ -s /tmp/gk/sudo.gk.error ]]; then  # If no error reported, we will allow to fail silently
 		if grep "command as another user" /tmp/gk/sudo.gk.error; then
 			err_exit1 "$(tail -n 3 /tmp/gk/sudo.gk.error)"
 		else
 			sed -E -n -i '/protocol specified|ToQuit/!p' /tmp/gk/sudo.gk.error
 			sed -E -n -i '/assertion|isPrimaryInstance|Initializing|QDir|usershare/!p' /tmp/gk/sudo.gk.error
-			err_exit1 "Error! if cryptic, possibly from unclean exit of child process
- $(cat /tmp/gk/sudo.gk.error)"
+			err_exit_file "gksudo2 Error" "Error! if cryptic, possibly from unclean exit of child process" /tmp/gk/sudo.gk.error
 		fi
 	fi
-else  # succeeded, but check errors/warnings
-	cleanup_files_dbus 
-	if [[ -s /tmp/gk/sudo.gk.error ]]; then
-		#  Filter some normally superfluous warnings from stderr/stdout
-		tail -n 2 /tmp/gk/sudo.gk.error > /tmp/gk/parsed-error 
-		if ! grep -E 'uninitialized|exiting|assertion|Bind on socket|isPrimaryInstance|WARNING|kdeinit5|Failed to connect|Initializing|QDir|ToQuit|net usershare|dictionaries|Activat|Success' /tmp/gk/parsed-error; then
-			sed -i '/^[[:space:]]*$/d' /tmp/gk/sudo.gk.error
-			sed -E -n -i '/dictionaries|protocol specified|ToQuit|WARNING|usershare info/!p' /tmp/gk/sudo.gk.error
-			sed -E -n -i '/Gtk-CRITICAL|uninitialized|assertion|isPrimaryInstance|Initializing|QDir|send signal/!p' /tmp/gk/sudo.gk.error
-			sed -E -n -i '/Unexpected nullptr|Expected a KPluginFactory|changed|still attached|Shortcut/!p' /tmp/gk/sudo.gk.error
-			sed -E -n -i '/context|GpuChannel|GFileInfo|gfileinfo/!p' /tmp/gk/sudo.gk.error
-			sed -E -n -i '/QThread|"wayland"|refused|viewproperties/!p' /tmp/gk/sudo.gk.error
-			err_len=$(wc -l < /tmp/gk/sudo.gk.error)
-			if [[ "$err_len" -gt 5 ]]; then
-				zenity --warning --title="gksudo2 Warning" --text="$(head -n 5 /tmp/gk/sudo.gk.error)
-$(tail -n 3 /tmp/gk/sudo.gk.error)" --no-wrap --no-markup 2>/dev/null
-			elif [[ "$err_len" -ne 0 ]]; then
-				zenity --warning --title="gksudo2 Warning" --text="$(cat /tmp/gk/sudo.gk.error)" --no-wrap --no-markup 2>/dev/null
-			fi
+elif [[ -s /tmp/gk/sudo.gk.error ]]; then  # succeeded, but check errors/warnings
+ 	#  Filter some normally superfluous warnings from stderr/stdout
+	tail -n 2 /tmp/gk/sudo.gk.error > /tmp/gk/parsed-error 
+	if ! grep -E 'uninitialized|exiting|assertion|Bind on socket|isPrimaryInstance|WARNING|kdeinit5|Failed to connect|Initializing|QDir|ToQuit|net usershare|dictionaries|Activat|Success|portal.Error' /tmp/gk/parsed-error; then
+		sed -i '/^[[:space:]]*$/d' /tmp/gk/sudo.gk.error
+		sed -E -n -i '/dictionaries|protocol specified|ToQuit|WARNING|usershare info/!p' /tmp/gk/sudo.gk.error
+		sed -E -n -i '/Gtk-CRITICAL|uninitialized|assertion|isPrimaryInstance|Initializing|QDir|send signal/!p' /tmp/gk/sudo.gk.error
+		sed -E -n -i '/Unexpected nullptr|Expected a KPluginFactory|changed|still attached|Shortcut/!p' /tmp/gk/sudo.gk.error
+		sed -E -n -i '/context|GpuChannel|GFileInfo|gfileinfo/!p' /tmp/gk/sudo.gk.error
+		sed -E -n -i '/QThread|"wayland"|refused|viewproperties/!p' /tmp/gk/sudo.gk.error
+		if grep -q '[^[:space:]]' /tmp/gk/sudo.gk.error ; then # if not just white space
+			err_exit_file "gksudo2 Warning" "" /tmp/gk/sudo.gk.error
 		fi
 	fi
 fi
-
-rm $xauth_gksudo 2> /dev/null
-rm /tmp/gk/gk-env-cmd 2> /dev/null
-rm /tmp/gk/sudo.gk.error 2> /dev/null
-if [[ -d "$as_usr_rundir" ]]; then
-	umount "$as_usr_rundir/gvfs" 2> /dev/null
-	umount "$as_usr_rundir/doc" 2> /dev/null
-	rm -R $as_usr_rundir
-fi
-gk_instances=$(pgrep -c gksudo2-su)
-if [[ $XDG_SESSION_TYPE = "wayland" ]] && [[ $gk_instances -lt 2 ]]; then
-	chmod 0700 $orig_xdg_rundir
-	chmod 0755 $wayland_socket
-fi
+finish_cleanup
 exit 0
-
